//
//  Schools.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class Schools: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _schools: [String]?
    
    class func dynamoDBTableName() -> String {
        
        return "timbancu-mobilehub-603959887-Schools"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_schools" : "schools",
        ]
    }
}
